apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: |
        This workspace is shared among all the pipeline tasks to read/write common resources
      name: source
  tasks:
    - name: alauda-build-image
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: alauda-build-image
      workspaces:
        - name: source
          workspace: source
      runAfter: []
      when: []
      params:
        - name: container-image
          value: build-harbor.alauda.cn/3rdparty/argoproj/argocd
        - name: container-image-tag
          value: $(build.git.version.short)
        - name: labels
          value:
            - branch=$(build.git.branch.name)
            - commit=$(build.git.lastCommit.id)
        - name: build-extra-args
          value: --build-arg=BASE_IMAGE=docker-mirrors.alauda.cn/library/ubuntu:24.04
            --build-arg=GO_IMAGE=docker-mirrors.alauda.cn/library/golang:1.24.4
            --build-arg=NODE_IMAGE=build-harbor.alauda.cn/acp/base/node:23.0.0
  git:
    options:
      depth: 1
      timeout: 20m
      retries: 3
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
  runTemplate:
    spec:
      taskRunSpecs: []
